# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.kernelPackages = pkgs.linuxPackages_latest;

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "nvme"
    "usbhid"
    # "usb_storage"
    "sd_mod"
    "ahci"
  ];
  boot.initrd.kernelModules = [ "dm-snapshot" ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];
  # fileSystems, swapDevices, and boot.initrd.luks.devices are now managed by disko

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  # Windows dual-boot via limine chainloading.
  # After installing NixOS, boot a Windows installer USB and repair the
  # Windows bootloader so it lives on its own ESP on the Windows SSD:
  #   1. Boot Windows installer USB → "Repair your computer" → Command Prompt
  #   2. Run: bcdboot C:\Windows /f UEFI
  #      (if needed, use diskpart to create/assign an ESP on the Windows SSD first)
  #   3. Find the Windows ESP's partition GUID:
  #      lsblk -o NAME,SIZE,FSTYPE,PARTUUID,PARTLABEL
  #   4. Replace the PARTUUID placeholder below and rebuild.
  boot.loader.limine.extraEntries = ''
    /Windows
        protocol: efi
        path: guid(5cede495-b0bb-45bc-b761-000a9c9e964e):/EFI/Microsoft/Boot/bootmgfw.efi
  '';

  # Optional: mount the data SSD (not managed by disko)
  # Find the device with: ls -l /dev/disk/by-id/ | grep nvme
  fileSystems."/mnt/vault" = {
    device = "/dev/disk/by-id/ata-Samsung_SSD_860_EVO_2TB_S597NJ0NB07777B-part1";
    fsType = "ext4";
    options = [
      "defaults"
      "nofail"
    ];
  };
}
