name: Update Flake
on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v16

      - name: Update flake.lock and Create PR
        id: update
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          # Using your PAT allows the PR to trigger the 'check.yml' workflow
          token: ${{ secrets.PAT_TOKEN }}
          pr-title: "chore: flake update"

      - name: Enable Auto-Merge
        # This tells GitHub to merge it once the checks (from the next file) pass
        if: steps.update.outputs.pull-request-operation == 'created'
        run: gh pr merge --auto --squash "${{ steps.update.outputs.pull-request-number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
