name: Update Flake
on:
  schedule:
    - cron: "0 9 * * *" # Runs daily at 9 AM UTC
  workflow_dispatch: # Allows you to trigger it manually

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v16

      - name: Update flake.lock and Create PR
        id: update
        uses: DeterminateSystems/update-flake-lock@v24
        with:
          token: ${{ secrets.PAT_TOKEN }}
          pr-title: "chore: flake update"

      - name: Enable Auto-Merge
        # Triggers whether it's a brand new PR or just adding new commits to yesterday's open PR
        if: steps.update.outputs.pull-request-operation == 'created' || steps.update.outputs.pull-request-operation == 'updated'
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        run: |
          echo "Giving GitHub 5 seconds to register the Ruleset for this PR..."
          sleep 5
          gh pr merge --auto --squash "${{ steps.update.outputs.pull-request-number }}"
